"""M3U8 file generator: produces standard IPTV channel playlists."""

import aiohttp
import asyncio
import hashlib
import json
import logging
import os
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from . import ChannelRecord, StreamStatus
from .classifier import get_group_order
from .config import PROJECT_ROOT, get_generator_config

logger = logging.getLogger(__name__)

LOGOS_FILE = PROJECT_ROOT / "data" / "logos.json"
LOGOS_CACHE_DIR = PROJECT_ROOT / "data" / "logos"

# Channel state store key
CHANNELS_STORE_KEY = "channels"

# M3U8 header template (with optional tvg-url for EPG)
def _m3u8_header(total: int, alive: int) -> str:
    """Generate m3u8 header, optionally including tvg-url for EPG auto-discovery."""
    from .epg import get_epg_source_url
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    epg_source = get_epg_source_url()
    if epg_source:
        extm3u = f'#EXTM3U url-tvg="{epg_source}"'
    else:
        extm3u = '#EXTM3U'
    lines = [
        extm3u,
        f'# Generated by LivePool at {timestamp}',
        f'# Total: {total} channels, {alive} alive',
    ]
    lines.append('')
    return '\n'.join(lines) + '\n'


def _load_logos() -> dict:
    """Load channel name → logo URL mapping."""
    if not LOGOS_FILE.exists():
        return {}
    try:
        return json.loads(LOGOS_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _match_logo(name: str, logos: dict) -> str:
    """Find logo URL for a channel by partial name match."""
    name_clean = name.lower().replace(" ", "").replace("-", "").replace("_", "")
    best = ("", 0)
    for key, url in logos.items():
        key_clean = key.lower().replace(" ", "").replace("-", "").replace("_", "")
        if key_clean in name_clean and len(key_clean) > best[1]:
            best = (url, len(key_clean))
    return best[0]

def _guess_ext(url: str) -> str:
    """Extract image extension from a logo URL."""
    path = url.rsplit("?", 1)[0].rsplit("#", 1)[0]
    _, dot_ext = path.rsplit(".", 1) if "." in path.rsplit("/", 1)[-1] else ("", "")
    ext = f".{dot_ext.lower()}" if dot_ext.lower() in ("png", "jpg", "jpeg", "gif", "svg", "webp") else ".png"
    return ext


async def cache_logos(records: List[ChannelRecord]) -> Dict[str, str]:
    """Download missing channel logos to ``output/logos/``.

    Returns a mapping of original logo URL → local URL path
    (e.g. ``https://example.com/logo.png → /logos/a1b2c3d4e5f6.png``).

    Already-cached logos are skipped.  Failed / timed-out downloads are
    silently skipped — the m3u8 will keep the original remote URL.
    """
    LOGOS_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    fallback_logos = _load_logos()

    # Collect unique logo URLs from alive records
    urls: set = set()
    for r in records:
        url = r.tvg_logo or _match_logo(r.name, fallback_logos)
        if url and (url.startswith("http://") or url.startswith("https://")):
            urls.add(url)

    if not urls:
        return {}

    # Build manifest: original URL → local path
    manifest: Dict[str, str] = {}
    to_download: List[tuple] = []
    for url in urls:
        ext = _guess_ext(url)
        h = hashlib.md5(url.encode(), usedforsecurity=False).hexdigest()[:12]
        fname = f"{h}{ext}"
        local_path = LOGOS_CACHE_DIR / fname
        manifest[url] = f"/logos/{fname}"
        if not local_path.exists():
            to_download.append((url, local_path))

    if not to_download:
        logger.info(f"Logo cache: all {len(manifest)} logos already cached")
        return manifest

    # Download missing logos concurrently — share one session for keep-alive reuse.
    # Remove from manifest on failure so the m3u8 keeps the original remote URL.
    sem = asyncio.Semaphore(10)
    downloaded = 0
    timeout = aiohttp.ClientTimeout(total=8, connect=3)

    async def _dl(url: str, dest: Path, sess: aiohttp.ClientSession) -> None:
        nonlocal downloaded
        async with sem:
            try:
                async with sess.get(url, allow_redirects=True) as resp:
                    if resp.status == 200:
                        data = await resp.read()
                        if data:
                            dest.write_bytes(data)
                            downloaded += 1
                    else:
                        del manifest[url]
                        logger.debug(f"Logo cache: HTTP {resp.status} for {url}")
            except asyncio.CancelledError:
                raise
            except Exception:
                del manifest[url]
                logger.debug(f"Logo cache: download failed for {url}")

    async with aiohttp.ClientSession(timeout=timeout) as _session:
        await asyncio.gather(*[_dl(url, dest, _session) for url, dest in to_download])

    logger.info(
        f"Logo cache: {downloaded} downloaded, "
        f"{len(to_download) - downloaded} failed out of {len(to_download)}"
    )
    return manifest


# EXTINF template
EXTINF_TMPL = (
    '#EXTINF:-1 group-title="{group}"'
    ' tvg-name="{name}"'
    ' tvg-id="{tvg_id}"'
    ' tvg-logo="{tvg_logo}"'
    '{resolution_attr}'
    ',{name}\n'
    '{url}\n'
)


def _atomic_write_text(path: Path, content: str) -> None:
    """Write content atomically: temp file then rename, preventing partial reads."""
    fd, tmp_path = tempfile.mkstemp(dir=path.parent, prefix=path.name + ".")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.rename(tmp_path, path)
    except BaseException:
        try:
            os.unlink(tmp_path)
        except Exception:
            pass
        raise


def generate(
    records: List[ChannelRecord],
    output_dir: Optional[Path] = None,
    main_file: Optional[str] = None,
    logo_cache: Optional[Dict[str, str]] = None,
) -> Path:
    """Generate m3u8 output file from classified channel records.

    Args:
        records: Classified channel records (alive only).
        output_dir: Directory for output.
        main_file: Filename for output.
        logo_cache: Mapping of original logo URLs to local paths,
                    returned by :func:`cache_logos`.  When provided,
                    ``tvg-logo`` attributes point at the local copy.

    Returns:
        Path to the output file.
    """
    cfg = get_generator_config()
    output_dir = output_dir or PROJECT_ROOT / cfg.get("output_dir", "data")
    main_file = main_file or cfg.get("main_file", "live.m3u8")

    output_dir = Path(output_dir) if not isinstance(output_dir, Path) else output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    # Group records (for rendering order, not per-group files)
    groups = _group_records(records)

    # Generate combined file — atomic write via temp + rename
    main_path = output_dir / main_file
    content = _render_m3u8(groups, records, logo_cache=logo_cache)
    _atomic_write_text(main_path, content)
    logger.info(f"Generated m3u8: {main_path} ({len(records)} channels)")

    return main_path


def _group_records(records: List[ChannelRecord]) -> Dict[str, List[ChannelRecord]]:
    """Group records by their group label, sorted by configured order."""
    group_order = get_group_order()
    groups: Dict[str, List[ChannelRecord]] = {}

    for r in records:
        groups.setdefault(r.group, []).append(r)

    # Sort groups by configured order
    ordered: Dict[str, List[ChannelRecord]] = {}
    for g in group_order:
        if g in groups:
            ordered[g] = groups.pop(g)
    # Append any remaining groups not in order list
    for g in sorted(groups.keys()):
        ordered[g] = groups[g]

    return ordered


def _render_m3u8(
    groups: Dict[str, List[ChannelRecord]],
    all_records: List[ChannelRecord],
    logo_cache: Optional[Dict[str, str]] = None,
) -> str:
    """Render a complete m3u8 file from grouped records."""
    alive = sum(1 for r in all_records if r.status == StreamStatus.ALIVE)
    fallback_logos = _load_logos()

    parts = [_m3u8_header(len(all_records), alive)]

    for group_name in groups:
        for r in groups[group_name]:
            resolution_attr = f' tvg-resolution="{r.resolution}"' if r.resolution else ""
            # Prefer source logo; fall back to logos.json; then local cache override
            logo = r.tvg_logo or _match_logo(r.name, fallback_logos)
            if logo_cache and logo in logo_cache:
                logo = logo_cache[logo]
            # Escape literal braces in field values to prevent .format() crash
            _esc = lambda s: s.replace("{", "{{").replace("}", "}}")
            parts.append(
                EXTINF_TMPL.format(
                    group=_esc(r.group),
                    name=_esc(r.name),
                    tvg_id=_esc(r.tvg_id or r.id),
                    tvg_logo=_esc(logo),
                    resolution_attr=_esc(resolution_attr),
                    url=_esc(r.url),
                )
            )
        parts.append("")

    return "".join(parts)


async def save_state(records: List[ChannelRecord]) -> None:
    """Persist channel state — upsert new records, preserve favorited channels."""
    from .store import _get_db, _ensure_tables, DB_PATH
    import json as _json
    import sqlite3 as _sqlite3

    # Collect incoming channel IDs
    incoming = {r.id for r in records}

    db = await _get_db()
    try:
        await _ensure_tables(db, "channels")

        # Upsert each record (INSERT OR REPLACE)
        saved = 0
        for r in records:
            await db.execute(
                """INSERT OR REPLACE INTO channels
                   (id, name, url, "group", status, latency_ms, resolution,
                    last_check, last_alive, source, tvg_id, tvg_logo,
                    has_cors, has_video, score)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                (r.id, r.name, r.url, r.group, r.status.value, r.latency_ms,
                 r.resolution, r.last_check, r.last_alive, r.source, r.tvg_id,
                 r.tvg_logo, int(r.has_cors), int(r.has_video), r.score),
            )
            saved += 1

        # Delete channels no longer present — but KEEP any that are favorited
        _fav_ids: set = set()
        try:
            _conn = _sqlite3.connect(str(DB_PATH))
            _conn.row_factory = _sqlite3.Row
            for _row in _conn.execute("SELECT favorites FROM users").fetchall():
                _fav = _row["favorites"]
                if isinstance(_fav, str):
                    try:
                        _fav = _json.loads(_fav)
                    except Exception:
                        _fav = []
                for _fid in _fav:
                    if isinstance(_fid, str) and _fid:
                        _fav_ids.add(_fid)
            _conn.close()
        except Exception:
            pass

        _protected = incoming | _fav_ids
        if _protected:
            _placeholders = ",".join("?" for _ in _protected)
            await db.execute(f"DELETE FROM channels WHERE id NOT IN ({_placeholders})", list(_protected))
        else:
            await db.execute("DELETE FROM channels")

        await db.commit()
        logger.info(f"Channel state saved: {saved} upserted, {len(incoming)} active, {len(_fav_ids)} favorited")
    finally:
        await db.close()


def load_state() -> List[ChannelRecord]:
    """Load channel state from store."""
    from .store import get_channels_store

    store = get_channels_store()
    records = []
    for d in store.all():
        records.append(ChannelRecord(
            id=d.get("id", ""), name=d.get("name", ""), url=d.get("url", ""),
            group=d.get("group", ""), status=StreamStatus(d.get("status", "pending")),
            latency_ms=d.get("latency_ms", 0.0), resolution=d.get("resolution", ""),
            last_check=d.get("last_check", ""), last_alive=d.get("last_alive", ""),
            source=d.get("source", ""), tvg_id=d.get("tvg_id", ""),
            tvg_logo=d.get("tvg_logo", ""),
            has_cors=d.get("has_cors", False), has_video=d.get("has_video", False),
            score=d.get("score", 0.0),
        ))
    return records
